### ISSUE TITLE
Just FYI - there is a similar solution Ingreedy

### ISSUE THREAD

**Issue by synergiator** [openculinary/ingredient-parser#20]
Hi there @jayaddison! Not a bug, just FYI.
.. it's written in Ruby and as it seems no more maintained for longer time, but it has been around for some years. [GitHub forks overview](https://techgaun.github.io/active-forks/index.html#iancanderson/ingreedy).

If you like to discuss and collaborate regarding "foodie programming/data science", please join [Slack](https://join.slack.com/t/openfoodbroker/shared_invite/zt-e01u7eep-D9GR3Ol4AMTrIQD0orT1HQ) at [Open Food Broker](https://github.com/openfoodbroker/openfoodbroker.github.io).

kind regards
Peter

**Comment by jayaddison** [comment]
Thanks @synergiator; as it happens we're using a [Python re-implementation of ingreedy](https://pypi.org/project/ingreedypy/) as a [dependency](https://github.com/openculinary/ingredient-parser/blob/d8542ef0c22a9986473f211559a85ab4ecc3cfb8/Pipfile#L12) in the application (some edits have been made, but most of the credit goes to the original authors).

Currently I'm near-zero-Slack but I will take a look at the organization.  It's great to see more open recipe technology developing.
